server:
  port: 8081

spring:
  application:
    name: auth

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration-ms: ${ACCESS_TOKEN_EXP}
  refresh-token-expiration-ms: ${REFRESH_TOKEN_EXP}

gateway:
  internal-secret: ${GATEWAY_INTERNAL_SECRET}

application:
  auth:
    cookie-path: /
  config:
    user-url: ${USER_SERVICE_URL:http://localhost:8080/api/v1/users}

eureka:
  instance:
    hostname: ${EUREKA_HOST:localhost}
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka

