server:
  port: ${GATEWAY_SERVICE_PORT:8080}

jwt:
  secret: ${JWT_SECRET}
gateway:
  internal-secret: ${GATEWAY_INTERNAL_SECRET}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.cors: DEBUG

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        # --- Rutas de AUTENTICACIÓN (sin filtro de auth ni bypass, solo passthrough) ---
        - id: auth-signin
          uri: lb://auth
          predicates:
            - Path=/api/v1/auth/signin
            - Method=POST

        - id: auth-signup
          uri: lb://auth
          predicates:
            - Path=/api/v1/auth/signup
            - Method=POST

        # --- Rutas de Auth que REQUIEREN JWT (para usuario final) ---
        - id: auth-signout-protected
          uri: lb://auth
          predicates:
            - Path=/api/v1/auth/signout
            - Method=GET
          filters:
            - AuthenticationFilter

        - id: auth-refresh-token-protected
          uri: lb://auth
          predicates:
            - Path=/api/v1/auth/refresh-token
            - Method=POST
          filters:
            - AuthenticationFilter

        # --- Rutas de COMUNICACIÓN INTERNA (Servicio a Servicio usando AuthBypassFilter) ---
        - id: user-service-internal-get-by-email
          uri: lb://user
          predicates:
            - Path=/api/v1/users/email/{email}
            - Method=GET
            - Header=X-Internal-Secret, ${GATEWAY_INTERNAL_SECRET}
          filters:
            - AuthBypassFilter

        - id: user-service-internal-create-user
          uri: lb://user
          predicates:
            - Path=/api/v1/users
            - Method=POST
            - Header=X-Internal-Secret, ${GATEWAY_INTERNAL_SECRET}
          filters:
            - AuthBypassFilter

        # --- Rutas PROTEGIDAS PARA USUARIOS FINALES (Requieren AuthenticationFilter) ---
        - id: service-user-route-protected
          uri: lb://user
          predicates:
            - Path=/api/v1/users/**
          filters:
            - AuthenticationFilter

        - id: service-board-route-protected
          uri: lb://board
          predicates:
            - Path=/api/v1/boards/**
          filters:
            - AuthenticationFilter

        - id: service-task-route-protected
          uri: lb://task
          predicates:
            - Path=/api/v1/tasks/**
          filters:
            - AuthenticationFilter

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka